# Generated by Django 4.2.2 on 2023-07-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Card',
        ),
    ]
